# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWZkMzRiNzlmMmIzYTA5NmRmNThmMGRlMWVkMzFkNmE4ODEwNjA4NWM2MDA5NGY2OGM2MjgxOTMyYzNmNTIzYmMwYTUzODVmNmU4MWZiZjU3MmY0Mjc4NjkxMjQzZWQ3NWMzZThlNTdjYTZkMmFmMGNmYWVjYzc3MjkzYWMzZDg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
